"""Structural (HTML-level) Document Diff engine — deterministic, no LLM.

The sibling of :mod:`engines.document_diff`. That engine flattens both
documents to plain text and diffs a token stream, which loses every bit of
structure a ``.docx`` carries: headings, paragraph boundaries, list markers
and — most damagingly for the bilingual contract templates this is used on —
tables, whose rows collapse into pipe-joined run-on lines. This engine keeps
the structure instead:

1. Both ``.docx`` files are converted to real HTML by ``mammoth`` (``<h1>``,
   ``<p>``, ``<table><tr><td>``, ``<ul><li>``, ``<strong>``, …).
2. That HTML is tokenized so a token is **a whole tag**, a whitespace run, a
   word, or a single punctuation mark (``_HTML_TOKEN_RE``), and the same
   ``difflib.SequenceMatcher`` word diff runs over those tokens.
3. Tags flow through untouched; only changed *word* tokens get wrapped in
   ``<del class="seg-delete">`` / ``<ins class="seg-insert">``.

Because the two documents are nearly always the same template with different
filled-in values, the tag tokens line up as ``equal`` and only genuinely
changed words get marked — the result is a Word-style tracked-changes view
that still renders as a real formatted document.

Return shape (``render: "html"``) matches what the Angular redline view
already expects — see ``DocumentDiffResult`` in
``frontend/src/app/docdiff/docdiff.service.ts`` and the ``render === 'html'``
branch of ``docdiff/cases/case-detail.component.html``:

.. code-block:: python

    {
        "render": "html",
        "identical": bool,
        "similarity": float,      # over TEXT tokens only — see below
        "summary": {"insertions", "deletions", "replacements", "changes"},
        "changes": [{"id", "type", "before", "after", "possibleMissingSection"}],
        "html": str,              # the merged redline document
    }

Notes on two deliberate choices:

- **Anchors ride on ``class``, not ``id``.** The frontend renders ``html``
  through Angular's ``[innerHTML]``, whose sanitizer drops ``id`` but keeps
  ``class`` verbatim, so the click-to-jump anchor is a second class
  (``doc-change-<id>``) that ``jumpToChange()`` looks up.
- **``similarity`` is measured over text, not markup.** Diffing the token
  stream includes tag tokens, and two fills of the same template share every
  tag — which would report ~99% similarity even when a guaranteed amount
  changed. The ratio here is computed over the *visible words* of both
  documents so the headline stat means "how similar is the content".

Tag balance: a changed span routinely begins and ends mid-element, so markers
are emitted per contiguous *text* run rather than around the span as a whole
(see :func:`_wrap_runs`) — wrapping the span would produce misnested markup
whose repair silently drops the marking from everything past the first end
tag. The final ``BeautifulSoup`` re-parse remains as a backstop, the same way
a browser fixes up slightly malformed HTML.
"""
from __future__ import annotations

import difflib
import re
from pathlib import Path
from typing import Any, NamedTuple

import mammoth
from bs4 import BeautifulSoup

# A token is a whole tag, a run of whitespace, a word, or a single punctuation
# character. Joining tokens back reproduces the HTML exactly.
#
# Punctuation is its own token rather than part of the word beside it. When it
# was glued on, a trailing period made the last surviving word of a truncated
# clause unequal to its counterpart ("Guarantee" vs "Guarantee."), so
# SequenceMatcher could not align it and reported the whole span as a
# *replacement* of "Guarantee … that Article." by "Guarantee." — dragging an
# unchanged word into the change and mislabelling a pure deletion. Split off,
# the word matches, the period matches, and only the removed clause is flagged.
#
# Punctuation *inside* a word stays part of it, so amounts and decimals survive
# as one token ("25,000,000", "2.5") instead of shattering into digit runs.
# \w is Unicode-aware, which keeps the bilingual Arabic templates intact.
_HTML_TOKEN_RE = re.compile(r"<[^>]+>|\s+|\w+(?:[.,'’/\-]\w+)*|[^\s<]|<")

_WORD_RE = re.compile(r"\S+")

# A deletion this many words or more reads as a whole clause/section going
# missing rather than an edited value, and gets flagged in the changes table.
LARGE_SECTION_WORD_THRESHOLD = 40


class ConvertedDocx(NamedTuple):
    """A ``.docx`` rendered to HTML, plus the images left out of it."""

    html: str
    image_count: int


def docx_to_html(path: Path) -> ConvertedDocx:
    """Convert a ``.docx`` to structural HTML via mammoth, minus its images.

    Images are excluded from the comparison on purpose. In this service the
    ``original`` is always generated by docgen-service and the ``returned`` is
    the customer's signed copy, so the returned side carries a signature image
    the original cannot have. Diffing that would flag a change on every signed
    document — the one thing guaranteed to be there.

    They were already being ignored, but only as a side effect of
    ``html_to_text`` returning ``""`` for an ``<img>``, which left
    :func:`compare_documents_html` treating the span as not meaningful. That is
    an accident waiting to be "fixed"; dropping them here states the decision.

    Dropping at conversion rather than stripping afterwards matters for size:
    mammoth's default inlines every image as a base64 data URI, so one 2 MB
    scanned signature turns into ~2.6 MB of HTML that is then stored on the
    case and pushed through the browser's ``[innerHTML]``. The handler runs
    before that string is ever built.

    The count comes back so the caller can tell a reviewer an image was set
    aside, instead of leaving them to assume it was checked.
    """
    images = 0

    def count_and_drop(image: Any) -> list:
        """mammoth image handler; returning no nodes emits nothing."""
        nonlocal images
        images += 1
        return []

    with open(path, "rb") as handle:
        html = mammoth.convert_to_html(handle, convert_image=count_and_drop).value
    return ConvertedDocx(html, images)


def html_to_text(html: str) -> str:
    """Visible text of an HTML fragment, whitespace-collapsed."""
    text = BeautifulSoup(html, "html.parser").get_text(separator=" ")
    return re.sub(r"\s+", " ", text).strip()


def _is_tag_token(token: str) -> bool:
    return len(token) > 1 and token.startswith("<") and token.endswith(">")


def _wrap_runs(tokens: list[str], marker: str, css_class: str, anchor: str) -> str:
    """Wrap each run of *text* tokens in ``marker``, leaving tags outside.

    A changed span routinely starts and ends mid-element — deleting one row of
    a table spans ``2</p></td><td><p>Warehouse…``. Wrapping that whole span in
    a single ``<del>`` emits markup no parser accepts, and the repairing
    re-parse in :func:`compare_documents_html` fixes it the way a browser
    would: by closing the ``<del>`` at the first end tag it meets. Everything
    after that point then renders as ordinary text, so a deleted row showed
    only its first cell struck through while the rest — the asset description
    and its value — looked untouched. The ``changes`` list said the row was
    gone; the redline the reviewer actually reads did not.

    Wrapping each contiguous text run separately keeps every marker inside the
    element that owns its text, so nesting stays valid and nothing survives the
    re-parse unmarked. Whitespace-only runs are emitted bare: marking them adds
    no visible strike-through and would only widen the highlight.
    """
    parts: list[str] = []
    run: list[str] = []

    def flush() -> None:
        if not run:
            return
        text = "".join(run)
        if text.strip():
            parts.append(f'<{marker} class="{css_class}{anchor}">{text}</{marker}>')
        else:
            parts.append(text)
        run.clear()

    for token in tokens:
        if _is_tag_token(token):
            flush()
            parts.append(token)
        else:
            run.append(token)
    flush()
    return "".join(parts)


def _mark_structural_changes(soup: BeautifulSoup) -> None:
    """Flag rows and list items whose every word was added or removed.

    :func:`_wrap_runs` marks the *text* of a deleted table row, but the row
    itself still renders as an ordinary row — and the frontend shades a
    wholly-removed row via ``tr.seg-delete-block > td`` (see
    ``frontend/src/styles.css``), not via the inline strike-through. So any
    row, cell or list item whose visible words all sit inside ``<del>`` (or all
    inside ``<ins>``) gets the matching block class, carrying the
    ``doc-change-N`` anchors it contains so click-to-jump still lands.

    An element is skipped when an ancestor already carries the same class: the
    row is the meaningful unit, and shading its cells again changes nothing.
    """
    for element in soup.find_all(["tr", "td", "th", "li"]):
        words = _WORD_RE.findall(element.get_text(" "))
        if not words:
            continue
        for name, block_class in (("del", "seg-delete-block"), ("ins", "seg-insert-block")):
            markers = element.find_all(name)
            if not markers:
                continue
            marked = _WORD_RE.findall(" ".join(m.get_text(" ") for m in markers))
            if len(marked) != len(words):
                continue  # only part of the row changed — the inline mark says it
            if any(block_class in (a.get("class") or []) for a in element.parents):
                continue
            anchors = {
                cls
                for m in markers
                for cls in (m.get("class") or [])
                if cls.startswith("doc-change-")
            }
            element["class"] = (element.get("class") or []) + [block_class] + sorted(anchors)


def _is_large_removal(change_type: str, before_text: str) -> bool:
    return (
        change_type == "deletion"
        and len(_WORD_RE.findall(before_text)) >= LARGE_SECTION_WORD_THRESHOLD
    )


def compare_documents_html(original_html: str, returned_html: str) -> dict[str, Any]:
    """Diff two HTML renderings of a document into a redline HTML document.

    Args:
        original_html: HTML of the original document (see :func:`docx_to_html`).
        returned_html: HTML of the returned/signed copy.

    Returns:
        The ``render: "html"`` result dict described in the module docstring.
    """
    tokens_a = _HTML_TOKEN_RE.findall(original_html)
    tokens_b = _HTML_TOKEN_RE.findall(returned_html)

    matcher = difflib.SequenceMatcher(a=tokens_a, b=tokens_b, autojunk=False)

    out: list[str] = []
    changes: list[dict[str, Any]] = []
    counts = {"insertions": 0, "deletions": 0, "replacements": 0}
    count_key = {
        "deletion": "deletions",
        "insertion": "insertions",
        "replacement": "replacements",
    }
    tag_to_type = {"delete": "deletion", "insert": "insertion", "replace": "replacement"}
    next_id = 0

    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            out.append("".join(tokens_a[i1:i2]))
            continue

        before_tokens = tokens_a[i1:i2] if tag in ("delete", "replace") else []
        after_tokens = tokens_b[j1:j2] if tag in ("insert", "replace") else []
        before = "".join(before_tokens)
        after = "".join(after_tokens)

        before_text = html_to_text(before)
        after_text = html_to_text(after)

        # A span whose only difference is whitespace or markup carries no
        # visible change — emit it unwrapped so the document still renders,
        # but don't flag it as a change the reviewer has to look at.
        is_meaningful = bool(before_text or after_text)
        change_id = next_id if is_meaningful else None
        anchor = f" doc-change-{change_id}" if change_id is not None else ""

        if before_text:
            out.append(_wrap_runs(before_tokens, "del", "seg-delete", anchor))
        elif before:
            out.append(before)

        if after_text:
            out.append(_wrap_runs(after_tokens, "ins", "seg-insert", anchor))
        elif after:
            out.append(after)

        if not is_meaningful:
            continue

        change_type = tag_to_type[tag]
        changes.append(
            {
                "id": change_id,
                "type": change_type,
                "before": before_text,
                "after": after_text,
                "possibleMissingSection": _is_large_removal(change_type, before_text),
            }
        )
        counts[count_key[change_type]] += 1
        next_id += 1

    # See module docstring: similarity over visible words, not markup, so a
    # shared template's identical tags can't mask a changed value.
    words_a = _WORD_RE.findall(html_to_text(original_html))
    words_b = _WORD_RE.findall(html_to_text(returned_html))
    similarity = difflib.SequenceMatcher(a=words_a, b=words_b, autojunk=False).ratio()

    soup = BeautifulSoup("".join(out), "html.parser")
    _mark_structural_changes(soup)
    merged = str(soup)

    return {
        "render": "html",
        "identical": len(changes) == 0,
        "similarity": similarity,
        "summary": {**counts, "changes": len(changes)},
        "changes": changes,
        "html": merged,
    }
