"""org-wide roles + profile config overrides

Revision ID: 76daf17fe404
Revises: e82dd4ea83c2
Create Date: 2026-07-13 04:50:38.308157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76daf17fe404'
down_revision: Union[str, Sequence[str], None] = 'e82dd4ea83c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_config_overrides',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'key', name='uq_profile_config_key')
    )
    with op.batch_alter_table('profile_config_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_config_overrides_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_config_overrides_profile_id'), ['profile_id'], unique=False)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_profile_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))

    op.drop_table('memberships')
    # server defaults so the new NOT NULL columns backfill on populated tables
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('org_role', sa.String(length=16), nullable=False, server_default='maker')
        )
        batch_op.add_column(
            sa.Column('can_edit_config', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_edit_config')
        batch_op.drop_column('org_role')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    op.create_table('memberships',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('profile_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_id', name=op.f('uq_membership'))
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_profile_id'), ['profile_id'], unique=False)

    with op.batch_alter_table('profile_config_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_config_overrides_profile_id'))
        batch_op.drop_index(batch_op.f('ix_profile_config_overrides_key'))

    op.drop_table('profile_config_overrides')
    # ### end Alembic commands ###
